title: William Towler - Portfolio
author:
  name: William Towler
  email: william.j.towler@gmail.com
description: This is a test description.
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/MrWoafer" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/william-towler-8a37b42b3/" }
