title: William Towler - Portfolio
author:
  name: William Towler
  email: william.j.towler@gmail.com
github_username: MrWoafer
description: This is a test description.
theme: minima
minima:
  { platform: linkedin,       user_url: "https://www.linkedin.com/in/william-towler-8a37b42b3/" }
